/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyProdRouteImport } from './routes/verify-prod'
import { Route as IndexRouteImport } from './routes/index'

const VerifyProdRoute = VerifyProdRouteImport.update({
  id: '/verify-prod',
  path: '/verify-prod',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify-prod': typeof VerifyProdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify-prod': typeof VerifyProdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verify-prod': typeof VerifyProdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/verify-prod'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/verify-prod'
  id: '__root__' | '/' | '/verify-prod'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerifyProdRoute: typeof VerifyProdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-prod': {
      id: '/verify-prod'
      path: '/verify-prod'
      fullPath: '/verify-prod'
      preLoaderRoute: typeof VerifyProdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerifyProdRoute: VerifyProdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
